### ISSUE TITLE
Master错误拼写Mater

### ISSUE THREAD

**Issue by heysq** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#1]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码
1.3 了解Kubernetes集群，第5页 1.3.2小节
## 问题描述
“在Kubernetes集群中，除Mater以外的其他服务器被称为Node“
这个Mater应该为Master

**Comment by kubeguide** [comment]
感谢指正！
