### ISSUE TITLE
3.3 节配置目录勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#11]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

124

## 问题描述

在 /etc/kubelet.d 目录下放入 static-web.yaml 文件，内容如下：
应改为
在 /etc/kubernetes/manifests 目录下放入 static-web.yaml 文件，内容如下：

**Comment by kubeguide** [comment]
感谢指正！
