### ISSUE TITLE
3.5.2 节本地配置文件名勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#12]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

131

## 问题描述

在下面的示例中展示了将两个配置文件 server.xml 和 logging. properties 定义为
应改为
在下面的示例中展示了将两个配置文件 server.xml 和 logging.properties 定义为

说明：第二个配置文件名字有一个空格是多余的。

**Comment by kubeguide** [comment]
感谢指正！
