### ISSUE TITLE
3.5.2 节第三种类型的数据源勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#13]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

138 & 143

## 问题描述

第 138 页

--from-env-file: 表示基于指定的文件或者目录创建 ConfigMap
应改为
--from-literal: 表示将参数中指定的 “key#=value#” 创建为 ConfigMap 的数据内容

第 143 页

3）--from-literal: 表示基于指定的文件或者目录创建 ConfigMap
应改为
3）--from-literal: 表示将参数中指定的 “key#=value#” 创建为 ConfigMap 的数据内容

**Comment by kubeguide** [comment]
感谢指正！
