### ISSUE TITLE
3.5.4 节 Pod 名勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#14]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

151 & 152

## 问题描述

第 151 页

例 1，若 ConfigMap “cm-appvars” 不存在，则在 Pod “cm-test-pod-cm-optional” 的定
应改为
例 1，若 ConfigMap “cm-appvars” 不存在，则在 Pod “cm-test-pod-cm-env-optional” 的定

第 152 页

例 2，当 ConfigMap “cm-appconfigfiles” 不存在，则在 Pod “cm-test-pod-cm-volume-
应改为
例 2，当 ConfigMap “cm-appconfigfiles” 不存在，则在 Pod “cm-test-app-cm-volume-

Pod 配置文件 cm-test-pod-cm-volume-optional.yaml 的内容如下：
应改为
Pod 配置文件 cm-test-app-cm-volume-optional.yaml 的内容如下：

```
# kubectl create -f cm-test-pod-cm-volume-optional.yaml
pod/cm-test-app-cm-volume-optional created
```
应改为
```
# kubectl create -f cm-test-app-cm-volume-optional.yaml
pod/cm-test-app-cm-volume-optional created
```

说明：第 152 页第二和第三处修改建议可能是不需要的。我个人认为这里的例 2 与第 150 页内容有一个延续性，所以（配置文件和Pod 名）命名习惯也应该有一个延续性。

**Comment by kubeguide** [comment]
第151页的文件名是笔误

第152页的，源码文件名称都以xxx-pod-xxx命名，yaml内的metadata.name没有必须跟文件名保持一致

感谢指正！
