### ISSUE TITLE
3.6.3 节 metadata.annotation 勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#16]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

163

## 问题描述

metadata.annotation: Pod 的 Annotation 列表，每个 Annotation 都以 key 为文件名
应改为
metadata.annotations: Pod 的 Annotation 列表，每个 Annotation 都以 key 为文件名

**Comment by kubeguide** [comment]
感谢指正！
