### ISSUE TITLE
3.9.4 节查看边车容器日志的命令勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#18]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

192

## 问题描述

`# kubectl logs logs job-with-init-sidecar-t6mq2 -c log-reader`
应改为
`# kubectl logs job-with-init-sidecar-t6mq2 -c log-reader`

说明：按书中命令运行，会报如下错误
```
# kubectl logs logs job-with-init-sidecar-t6mq2 -c log-reader
Error from server (NotFound): pods "logs" not found
```

**Comment by kubeguide** [comment]
感谢指正！
