### ISSUE TITLE
4.3.3 节 updateStrategy.rollingUpdate 参数取整方式勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#23]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

216

## 问题描述

```
◎ spec.updateStrategy.rollingUpdate.maxUnavailable：...。如果该参数被设置为百分比，那么系统会先以
向下取整的方式计算出绝对值（整数）。...。
◎ spec.updateStrategy.rollingUpdate.maxSurge：...。如果该参数被设置为百分比，那么系统会先以
向下取整的方式计算出绝对值（整数）。...。
```

应改为

```
◎ spec.updateStrategy.rollingUpdate.maxUnavailable：...。如果该参数被设置为百分比，那么系统会先以
向上取整的方式计算出绝对值（整数）。...。
◎ spec.updateStrategy.rollingUpdate.maxSurge：...。如果该参数被设置为百分比，那么系统会先以
向上取整的方式计算出绝对值（整数），并且最小值为 1。...。
```

官方文档中关于 spec.updateStrategy.rollingUpdate.maxSurge 的描述为 “Absolute number is calculated from percentage by rounding up to **a minimum of 1**.”，我上面的翻译不够准确，请修正。

## 相关链接

https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/

**Comment by kubeguide** [comment]
感谢指正！
