### ISSUE TITLE
4.4.3 节 updateStrategy.rollingUpdate.maxUnavailable 参数取整方式勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#24]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

232

## 问题描述

分比，那么系统会先以向下取整的方式计算出绝对值（整数）。maxUnavailable 必须被设
应改为
分比，那么系统会先以向上取整的方式计算出绝对值（整数）。maxUnavailable 必须被设

## 相关链接

https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/stateful-set-v1/

**Comment by kubeguide** [comment]
感谢指正！
