### ISSUE TITLE
4.7.1 节格式中 DayofWeek 的说明勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#31]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

307

## 问题描述

`#  |  |  |  |  ----------  某星期的某一天（0~6，即星期日到星期一；7 在某些系统中表示星期日）`
应改为
`#  |  |  |  |  ----------  某星期的某一天（0~6，即星期日到星期六；7 在某些系统中表示星期日）`

**Comment by kubeguide** [comment]
感谢指正！
