### ISSUE TITLE
5.2.11 节 Toplogy 勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#33]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

347

## 问题描述

v1.28 版本开始该机制被称为拓扑感知路由（Toplogy Aware Routing）。
应改为
v1.28 版本开始该机制被称为拓扑感知路由（Topology Aware Routing）。

**Comment by kubeguide** [comment]
感谢指正！
