### ISSUE TITLE
5.3.3 节 nslookup redis-master 疑问

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#34]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

357

## 问题描述

```
# kubectl exec busybox -- nslookup redis-master
Server:     169.169.0.100
Address 1:  169.169.0.100

Name:      redis-master
Address 1： 169.169.8.10
```
在第6版 上册第 5 章前三个小节中我没有找到创建 redis-master 服务的代码。建议在这个命令中使用一个在本章中或者本书中前面已经创建过的服务（如 webapp, nginx 等）。

另外此命令的输出格式好像也有问题，在 5.2.9 节中运行 nslookup 命令的输出格式如下：
```
# nslookup webapp.default.svc.cluster.local
Server:         169.169.0.100
Address:        169.169.0.100#53

Name:    webapp.default.svc.cluster.local
Address： 169.169.140.242
```
注意：`# kubectl exec busybox -- nslookup kube-dns.kube-system` 命令的输出格式有同样的问题

**Comment by kubeguide** [comment]
感谢指正
1. 应该改成已经部署过的服务名称
2. nslookup命令的输出格式在跟busybox镜像的版本有关，以实际输出结果为准即可
