### ISSUE TITLE
5.6 Ingress 资源对象勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#36]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

378

## 问题描述

对象，用于将 Kubernetes 集群外的客户端请求路由到集群中部的服务上，同时提供了 7 层
应改为
对象，用于将 Kubernetes 集群外的客户端请求路由到集群中部署的服务上，同时提供了 7 层

**Comment by kubeguide** [comment]
感谢指正！
