### ISSUE TITLE
7.1.1 节单位勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#37]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

485, 493

## 问题描述

第 485 页
        按照这个计算公式得到以上 Node 可分配的资源量：CPU 总量为 16-1-0.5=14.5( GB )
应改为
        按照这个计算公式得到以上 Node 可分配的资源量：CPU 总量为 16-1-0.5=14.5（个）
或者
        按照这个计算公式得到以上 Node 可分配的资源量：CPU 总量为 16-1-0.5=14.5

第 493 页
        （ 1 ）cpu.shares=500MB，CPU=0.5 x 1024=512，查看对应的 cgroup 文件来验证：
应改为
        （ 1 ）cpu.shares=500m，CPU=0.5 x 1024=512，查看对应的 cgroup 文件来验证：

**Comment by kubeguide** [comment]
感谢指正！
