### ISSUE TITLE
2.2.6 节 calico.yaml 文件勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#4]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

61

## 问题描述

`# kubectl apply -f "https://docs.projectcalico.org/manifests/calico.yaml"`
该命令运行后的输出与书中描述不符，具体来说缺失了以下 4 行：
```
...
serviceaccount/calico-cni-plugin created
...
customresourcedefinition.apiextensions.k8s.io/bgpfilters.crd.projectcalico.org created
...
clusterrole.rbac.authorization.k8s.io/calico-cni-plugin created
...
clusterrolebinding.rbac.authorization.k8s.io/calico-cni-plugin created
...
```
在浏览器中输入：https://docs.projectcalico.org/manifests/calico.yaml
实际打开的网址是：https://calico-v3-25.netlify.app/archive/v3.25/manifests/calico.yaml
查看该文件的内容可以理解为什么上面会缺失 4 行。

下载 Calico v3.28.0 release, 然后使用该 release 中包含的 calico.yaml：
`# kubectl apply -f calico.yaml`
其输出与书中描述相符

**Comment by kubeguide** [comment]
感谢指正！
`https://docs.projectcalico.org/manifests/calico.yaml`的内容没有更新到最新版，应改为：
`kubectl apply -f "https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml"`
