### ISSUE TITLE
8.4.3 节删除 NetworkPolicy 勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#41]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

600

## 问题描述

部署完成后，除了删除名为 "grafana" 的 NetworkPolicy 之外，还需要删除名为 "prometheus-k8s" 的 NetworkPolicy。

如果没有删除 "prometheus-k8s" 这个 NetworkPolicy，则第 601 页通过 Node 的 32026 端口无法打开 Web 页面。

这个问题之前已经有人提出（可能是因为没有使用勘误模板而未被采纳），请参考 https://github.com/kubeguide/K8sDefinitiveGuide-V6-A-corrigendum/issues/21

**Comment by kubeguide** [comment]
感谢指正！
