### ISSUE TITLE
P45myweb-deploy.yml文件缩进问题

### ISSUE THREAD

**Issue by Von0115** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#5]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码
P45
## 问题描述
myweb-deploy.yaml中第23行缩进问题，- name 是 env 的一个子元素，因此它应该在 env 的下面，并与 env 保持相同的缩进级别。这样，value 也需要与 name 保持相同的缩进级别。

**Comment by kubeguide** [comment]
感谢指正！
