### ISSUE TITLE
2.3.4 节 /etc/kubernetes/controller-manager 文件勘误 （不确定）

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#7]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

77

## 问题描述

/etc/kubernetes/controller-manager 文件的 KUBE_CONTROLLER_MANAGER_ARGS 中：
`--service-account-private-key-file=/etc/kubernetes/pki/apiserver.key \`
应改为：
`--service-account-private-key-file=/etc/kubernetes/pki/sa.key \`

和 issue #6 一样，我不太确定这个修改是否正确。

## 相关链接
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#token-controller
https://kubernetes.io/docs/setup/best-practices/certificates/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Comment by kubeguide** [comment]
这个参数可以使用apiserver.key，也可以使用其他自定义key

感谢指正！
