### ISSUE TITLE
2.3.5 节部署 Calico CNI 网络插件命令勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#8]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

90

## 问题描述

`kubectl apply -f "https://docs.projectcalico.org/manifests/calico.yaml"`
应改为
`kubectl --kubeconfig=/etc/kubernetes/kubeconfig apply -f "https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml"`

关于 calico.yaml 的 URL 勘误已经在 issue #4 中提出，此处想要探讨是否应该在命令中加入 --kubeconfig flag。

我的理由如下：
1. 未加入 --kubeconfig flag 时运行命令会得到如下错误：
`error: error validating "https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml": error validating data: failed to download openapi: Get "http://localhost:8080/openapi/v2?timeout=32s": dial tcp [::1]:8080: connect: connection refused; if you choose to ignore these errors, turn validation off with --validate=false`
2. 在这一页上有三次 kubectl 命令的调用，其中两次都有加入 --kubeconfig flag。

也可以考虑第二种勘误方式：
参考第 57 页介绍的方式为 kubectl 设置客户端的身份配置文件：
`# export KUBECONFIG=/etc/kubernetes/kubeconfig`
则第 90 页三次 kubectl 命令的调用都将不需要 --kubeconfig flag。

**Comment by kubeguide** [comment]
两种方式都是可以的，文中可以改成都使用--kubeconfig flag：
kubectl apply -f "https://docs.projectcalico.org/manifests/calico.yaml"
应改为
kubectl --kubeconfig=/etc/kubernetes/kubeconfig apply -f "https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml"

感谢指正！
